# Site settings
title: Hake Blog
email: sam_hake@live.co.uk
description: > # this means to ignore newlines until "baseurl:"
  The personal blog of Sam Scott-Hake.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ss-hake.github.io" # the base hostname & protocol for your site
twitter_username: SS_Hake
github_username:  SS-Hake

# Build settings
markdown: kramdown